spring:
  application:
      name: artzip
  profiles:
    include:
      - aws
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB
  jwt:
    issuer: backfro
    accessToken:
      header: accessToken
      expiry-seconds: 1800
    refreshToken:
      header: refreshToken
      expiry-seconds: 604800
    blacklist:
      access-token: BlackList_AccessToken_
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error