package com.prgrms.datahandle.exhibition.domain;

public enum Area {
  SEOUL, BUSAN, DAEGU, INCHEON, DAEJEON, GWANGJU, ULSAN, SEJONG, GYEONGGI, GANGWON, CHUNGBUK, CHUNGNAM, JEONBUK, JEONNAM, GYEONGBUK, GYEONGNAM, JEJU
}
